GET http://localhost:9000 HTTP/1.1

###

GET http://localhost:9000/api/v1/movies HTTP/1.1

###

GET http://localhost:9000/api/v1/movies/2 HTTP/1.1

###

POST http://localhost:9000/api/v1/movies?name=IME_FILMA_OVDJE&genre=Documentary&rating=2&explicit=True HTTP/1.1

###

PUT http://localhost:9000/api/v1/movies/14?name=UPDATE&rating=3 HTTP/1.1

###

DELETE http://localhost:9000/api/v1/movies/14 HTTP/1.1
